// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";

export type CampaignStatus = "DRAFT" | "SCHEDULED" | "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED";

export type LeadStatus = "PENDING" | "QUEUED" | "SENT" | "OPENED" | "CLICKED" | "REPLIED" | "BOUNCED" | "UNSUBSCRIBED" | "FAILED";

export type EmailSendStatus = "QUEUED" | "SENDING" | "SENT" | "FAILED" | "BOUNCED";

export type SequenceType = "EMAIL" | "WAIT" | "MANUAL_TASK";

export type EmailProvider = "SMTP" | "GMAIL_API" | "OUTLOOK_API" | "SENDGRID" | "AWS_SES";

export type WarmupStatus = "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "PAUSED";

export type PlanCode = "FREE" | "STARTER" | "PROFESSIONAL" | "ENTERPRISE";

export type BillingPeriod = "MONTHLY" | "YEARLY";

export type EventType = "SENT" | "DELIVERED" | "OPENED" | "CLICKED" | "REPLIED" | "BOUNCED" | "UNSUBSCRIBED" | "COMPLAINED";

export interface AuthRequest extends Request {
  user: User;
}

export type StopSending = "REPLY" | "CLICK" | "OPEN";

export interface Organization {
  id: string;
  name: string;
  domain: string | null;
  phone: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  zip: string | null;
  industry: string | null;
  description: string | null;
  logoUrl: string | null;
  timezone: string;
  createdAt: Date;
  updatedAt: Date;
  users?: User[];
  senderAccounts?: SenderAccount[];
  campaigns?: Campaign[];
  leads?: Lead[];
  plans?: OrganizationPlan[];
  apiKeys?: ApiKey[];
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  password: string;
  phone: string | null;
  role: UserRole;
  profilePicture: string | null;
  isVerified: boolean;
  isActive: boolean;
  lastLoginAt: Date | null;
  timezone: string | null;
  otpCode: string | null;
  otpExpiresAt: Date | null;
  resetToken: string | null;
  resetTokenExpiresAt: Date | null;
  activationToken: string | null;
  activationTokenExpiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
  leadsUploaded?: Lead[];
  campaigns?: Campaign[];
}

export interface AccessToken {
  id: string;
  token: string;
  userId: string;
  expiresAt: Date;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ApiKey {
  id: string;
  name: string;
  key: string;
  lastUsedAt: Date | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
}

export interface SenderAccount {
  id: string;
  email: string;
  name: string | null;
  provider: EmailProvider;
  smtpHost: string | null;
  smtpPort: number | null;
  smtpUser: string | null;
  smtpPass: string | null;
  accessToken: string | null;
  refreshToken: string | null;
  tokenExpiry: Date | null;
  dailyLimit: number;
  hourlyLimit: number;
  minDelaySeconds: number;
  isEnabled: boolean;
  isVerified: boolean;
  warmupStatus: WarmupStatus;
  warmupStartedAt: Date | null;
  warmupDailyIncrement: number;
  signature: string | null;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
  runtime?: SenderRuntime[];
  emailSends?: EmailSend[];
  campaignSenders?: CampaignSender[];
}

export interface SenderRuntime {
  id: string;
  senderId: string;
  dayKey: string;
  sentToday: number;
  sentThisHour: number;
  hourKey: string | null;
  lastSentAt: Date | null;
  lockedAt: Date | null;
  lockedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
  sender?: SenderAccount;
}

export interface Campaign {
  id: string;
  name: string;
  description: string | null;
  status: CampaignStatus;
  timezone: string;
  sendDays: string[];
  windowStart: string;
  windowEnd: string;
  intervalMinutes: number;
  maxEmailsPerDay: number;
  sendAsPlainText: boolean;
  trackOpens: boolean;
  trackClicks: boolean;
  stopSending: StopSending;
  sendingPriority: number;
  autoPauseSameDomain: boolean;
  bounceRateThreshold: number;
  autoPauseOnHighBounce: boolean;
  includeUnsubscribeLink: boolean;
  unsubscribeText: string | null;
  createdAt: string;
  updatedAt: string;
  scheduledAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  orgId: string;
  nextTrigger: string | null;
  organization?: Organization;
  campaignLeads?: CampaignLead[] | [];
  createdById: string | null;
  createdBy?: User | null;
  sequences?: Sequence[] | [];
  leads?: Lead[] | [];
  senders?: CampaignSender[] | [];
  runtime?: CampaignRuntime | null;
  analytics?: CampaignAnalytics | null;
  emailSends?: EmailSend[] | [];
  sender_accounts: SenderAccount[] | [];
  campaignStats?: CampaignStats | null;
}

export interface CampaignStats {
  totalLeads: number;
  totalSequences: number;
  completedPercentage: number;
  emailsFailed: number;
  emailsQueued: number;
  emailsSent: number;
  leadsBounced: number;
  leadsCompleted: number;
  leadsPending: number;
  leadsReplied: number; 
  totalEmailsNeeded: number;
}

export interface CampaignSender {
  id: string;
  campaignId: string;
  senderId: string;
  weight: number;
  isActive: boolean;
  createdAt: string;
  campaign?: Campaign;
  sender?: SenderAccount;
}

export interface CampaignRuntime {
  id: string;
  campaignId: string;
  dayKey: string;
  sentToday: number;
  nextRunAt: string;
  lockedAt: string | null;
  lockedBy: string | null;
  createdAt: string;
  updatedAt: string;
  campaign?: Campaign;
}

export interface CampaignAnalytics {
  id: string;
  campaignId: string;
  totalLeads: number;
  leadsYetToStart: number;
  leadsInProgress: number;
  leadsCompleted: number;
  blockedLeads: number;
  sentCount: number;
  deliveredCount: number;
  openedCount: number;
  clickedCount: number;
  repliedCount: number;
  bouncedCount: number;
  unsubscribedCount: number;
  failedCount: number;
  openRate: number;
  clickRate: number;
  replyRate: number;
  bounceRate: number;
  createdAt: string;
  updatedAt: string;
  campaign?: Campaign;
}

export interface Sequence {
  id: string;
  campaignId: string;
  seqNumber: number;
  type: SequenceType;
  delayDays: number;
  delayHours: number;
  delayMinutes: number;
  subject: string | null;
  bodyHtml: string | null;
  bodyText: string | null;
  taskTitle: string | null;
  taskDescription: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  campaign?: Campaign;
  emailSends?: EmailSend[];
}

export interface Lead {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  company: string | null;
  designation: string | null;
  industry: string | null;
  linkedinUrl: string | null;
  website: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  customFields: JsonValue | null;
  isVerified: boolean;
  isBlocked: boolean;
  isUnsubscribed: boolean;
  unsubscribedAt: string | null;
  source: string | null;
  fileName: string | null;
  createdAt: string;
  updatedAt: string;
  orgId: string;
  organization?: Organization;
  uploadedById: string | null;
  uploadedBy?: User | null;
  campaigns?: CampaignLead[];
  emailSends?: EmailSend[];
  events?: EmailEvent[];
}

export interface CampaignLead {
  id: string;
  campaignId: string;
  leadId: string;
  status: LeadStatus;
  currentSequenceStep: number;
  nextSendAt: string | null;
  isStopped: boolean;
  stoppedAt: string | null;
  stoppedReason: string | null;
  lastSentAt: string | null;
  lastOpenedAt: string | null;
  lastClickedAt: string | null;
  lastRepliedAt: string | null;
  createdAt: string;
  updatedAt: string;
  campaign?: Campaign;
  lead?: Lead;
}

export interface EmailSend {
  id: string;
  status: EmailSendStatus;
  sequenceStep: number | null;
  providerMsgId: string | null;
  threadId: string | null;
  errorMessage: string | null;
  errorCode: string | null;
  attempts: number;
  lastAttemptAt: string | null;
  queuedAt: string;
  sentAt: string | null;
  createdAt: string;
  updatedAt: string;
  campaignId: string;
  campaign?: Campaign;
  senderId: string;
  sender?: SenderAccount;
  leadId: string;
  lead?: Lead;
  sequenceId: string | null;
  sequence?: Sequence | null;
  events?: EmailEvent[];
}

export interface EmailEvent {
  id: string;
  type: EventType;
  timestamp: string;
  ipAddress: string | null;
  userAgent: string | null;
  linkUrl: string | null;
  city: string | null;
  country: string | null;
  createdAt: string;
  emailSendId: string;
  emailSend?: EmailSend;
  leadId: string;
  lead?: Lead;
}

export interface Plan {
  id: number;
  code: PlanCode;
  name: string;
  description: string | null;
  priceMonthly: number | null;
  priceYearly: number | null;
  isContactSales: boolean;
  maxUsers: number | null;
  maxSenderAccounts: number | null;
  maxLeadsPerMonth: number | null;
  maxEmailsPerMonth: number | null;
  maxCampaigns: number | null;
  hasEmailVerification: boolean;
  hasEmailWarmup: boolean;
  hasUnifiedInbox: boolean;
  hasApiAccess: boolean;
  hasCustomDomain: boolean;
  hasAdvancedAnalytics: boolean;
  hasPrioritySupport: boolean;
  createdAt: string;
  updatedAt: string;
  subscriptions?: OrganizationPlan[];
}

export interface OrganizationPlan {
  id: number;
  orgId: string;
  planId: number;
  billingPeriod: BillingPeriod;
  isActive: boolean;
  startsAt: string;
  endsAt: string | null;
  emailsSentThisPeriod: number;
  leadsAddedThisPeriod: number;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  createdAt: string;
  updatedAt: string;
  organization?: Organization;
  plan?: Plan;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
