name: Deploy Frontend to Jooper Server


on:
 push:
   branches:
     - master


jobs:
 deploy:
   runs-on: ubuntu-latest


   steps:
     - name: ⬇️ Checkout Code
       uses: actions/checkout@v3


     - name: 📤 Copy files to server with SCP
       uses: appleboy/scp-action@v0.1.7
       with:
         host: ${{ secrets.SERVER_HOST }}
         username: ${{ secrets.SERVER_USER }}
         key: ${{ secrets.JOOPER_SSH_KEY }}
         source: "."
         target: "/root/apps/joop-leads-frontend"


     - name: 🚀 Run remote build and deploy commands
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.SERVER_HOST }}
         username: ${{ secrets.SERVER_USER }}
         key: ${{ secrets.JOOPER_SSH_KEY }}
         script: |
           export NVM_DIR="$HOME/.nvm"
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
           cd /root/apps/joop-leads-frontend
           npm install
           npm run build
           if [ -d dist ]; then
             sudo rsync -av --delete dist/ /var/www/joop-leads-frontend/
             sudo chown -R www-data:www-data /var/www/joop-leads-frontend/
             sudo chmod -R 755 /var/www/joop-leads-frontend/
             sudo systemctl restart nginx
           else
             echo '❌ Build failed, skipping deployment'
           fi
